# If you don't have an API key yet, register your application at:
# 
# <YourShopURL>/admin/api (e.g. "http://shopname.myshopify.com/admin/api")
#
# Be sure to conceal these credentials if you make your application code public.
# If you're using Git, put the following line in a file called .gitignore in your
# repository root:
# 
#   config/shopify.yml
# 
# If you're using SVN, you can run this command from the application root:
# 
#   svn propedit svn:ignore ./config/shopify.yml
#
# You can also load your API credentials from the environment variables 
# SHOPIFY_API_KEY and SHOPIFY_API_SECRET.
#
# If you are deploying to Heroku, you use config vars (http://docs.heroku.com/config-vars) for this purpose:
#
#   heroku config:add SHOPIFY_API_KEY=<%= api_key %> SHOPIFY_API_SECRET=<%= secret %>
development:
  api_key: 40c16a5e2baa8a9607201afc0c2a2f31
  secret: 0097fecade04110b5c7e20a7e9fdd5a7

test:
  api_key: 40c16a5e2baa8a9607201afc0c2a2f31
  secret: 0097fecade04110b5c7e20a7e9fdd5a7

production:
  api_key: <%= ENV[:SHOPIFY_API_KEY] %>
  secret: <%= ENV[:SHOPIFY_API_KEY] %>